# Fastfetch Installer — сохранённые пути
# Формат: относительный_путь=путь_назначения
# Удали строку — сбросится на дефолт

fastfetch/config.jsonc=/home/wpswa/.config/fastfetch/config.jsonc
ghostty/config=/home/wpswa/.config/ghostty/config
ghostty/config.ghostty=/home/wpswa/.config/ghostty/config.ghostty
nvim/lua/config/autocmds.lua=/home/wpswa/.config/nvim/lua/config/autocmds.lua
nvim/lua/config/keymaps.lua=/home/wpswa/.config/nvim/lua/config/keymaps.lua
nvim/lua/config/lazy.lua=/home/wpswa/.config/nvim/lua/config/lazy.lua
nvim/lua/config/options.lua=/home/wpswa/.config/nvim/lua/config/options.lua
nvim/lua/plugins/example.lua=/home/wpswa/.config/nvim/lua/plugins/example.lua
nvim/LICENSE=/home/wpswa/.config/nvim/LICENSE
nvim/README.md=/home/wpswa/.config/nvim/README.md
nvim/init.lua=/home/wpswa/.config/nvim/init.lua
nvim/lazy-lock.json=/home/wpswa/.config/nvim/lazy-lock.json
nvim/lazyvim.json=/home/wpswa/.config/nvim/lazyvim.json
nvim/stylua.toml=/home/wpswa/.config/nvim/stylua.toml
